#!/bin/sh

action="$1" # login / unlock
email=""
if [ "$action" = login ]; then
	email=" john+bitwarden@ankarstrom.se"
	[ -e /tmp/bw-key ] && rm /tmp/bw-key
	touch /tmp/bw-key
	chmod 600 /tmp/bw-key
fi

zenity --title Bitwarden --password \
	| eval "bw $action --raw$email" \
	> /tmp/bw-key

grep incorrect /tmp/bw-key && rm /tmp/bw-key

zenity --title Response --info --text "$(cat /tmp/bw-key)"
