#!/bin/sh

action="$1" # login / unlock
email=""
if [ "$action" = login ]; then
	email=" john+bitwarden@ankarstrom.se"
	[ -e /tmp/bw-key ] && rm /tmp/bw-key
	touch /tmp/bw-key
	chmod 600 /tmp/bw-key
fi

zenity --title Bitwarden --password \
	| eval "bw $action --raw$email" \
	> /tmp/bw-key

if $(grep incorrect /tmp/bw-key); then
	rm /tmp/bw-key
else
	[ -e /tmp/bw-accounts ] && rm /tmp/bw-accounts
	touch /tmp/bw-accounts
	chmod 600 /tmp/bw-accounts
	bw list items --session $(cat /tmp/bw-key) > /tmp/bw-accounts
fi

zenity --title Response --info --text "$(cat /tmp/bw-key)"
